version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 54321:5432
    volumes:
      - ./.ignore/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=stonks
      - POSTGRES_USER=stonks
      - TWELVE_DATA_API_KEY=bb6141c0a7c449949a766265877511b9
